# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XoloUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_XoloUi(object):
    def setupUi(self, XoloUi):
        XoloUi.setObjectName("XoloUi")
        XoloUi.resize(1366, 720)
        self.centralwidget = QtWidgets.QWidget(XoloUi)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-70, -20, 1531, 841))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("../GUI/bg/vecteezy_abstract-blue-circuit-digital-background_6736873.jpg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(610, 240, 111, 101))
        self.bg_2.setText("")
        self.bg_2.setPixmap(QtGui.QPixmap("../GUI/bg/Screenshot_20230423_000708_Microsoft 365 (Office) (2).png"))
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(510, 410, 111, 41))
        self.pushButton_1.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(226, 226, 218);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 410, 111, 41))
        self.pushButton_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(226, 226, 218);")
        self.pushButton_2.setObjectName("pushButton_2")
        XoloUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(XoloUi)
        QtCore.QMetaObject.connectSlotsByName(XoloUi)

    def retranslateUi(self, XoloUi):
        _translate = QtCore.QCoreApplication.translate
        XoloUi.setWindowTitle(_translate("XoloUi", "MainWindow"))
        self.pushButton_1.setText(_translate("XoloUi", "START"))
        self.pushButton_2.setText(_translate("XoloUi", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    XoloUi = QtWidgets.QMainWindow()
    ui = Ui_XoloUi()
    ui.setupUi(XoloUi)
    XoloUi.show()
    sys.exit(app.exec_())
